language: python

python:
  - 2.6
  - 2.7

install:
  - python setup.py install
  - pip install coveralls --use-mirrors

script:
  - nosetests -q --with-coverage --cover-erase --cover-package=bodhi

after_success:
  - coveralls
